### ISSUE TITLE
Thank you for providing such a nice tool & question

### ISSUE THREAD

**Issue by revast** [chg-hou/DawnlightSearch#2]
hello, I wanted to thank you very much for this nice piece of software.

I use swift search on windows, which also does searching the MFT of NTFS volumes.
Great to have that functionality on Linux! Even if it just works with NTFS file systems, it is more than welcome to instantly search through an 3 tb external harddisk.

The question I would have is, why would dawnlightSearch provide so many more entries in the database field?
/sys /proc etc - is this normal?

**Comment by chg-hou** [comment]
@revast 
It is normal. /sys /proc are the interfaces into the kernel using "file system"-style device drivers.
Pls see: [https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/Reference_Guide/ch-proc.html](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/Reference_Guide/ch-proc.html)
I did not exclude those folder by default.  You may add by clicking "Setting" -> "Change excluded folder".

**Comment by revast** [comment]
ok, thanks! I also found that your ppa refuses to work.

W: The repository 'http://ppa.launchpad.net/chg-hou/dawnlightsearch/ubuntu xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by chg-hou** [comment]
@revast 
I guess you edited the source file manually. It seems that the gpg key has not been imported successfully. You can confirm this by running
`apt-key list`
and checking whether the following lines existing:
> /etc/apt/trusted.gpg.d/chg-hou_ubuntu_dawnlightsearch.gpg
> pub   4096R/BD555200 2016-06-19
> uid                  Launchpad PPA for Chenguang Hou

Solution: 
`sudo add-apt-repository ppa:chg-hou/dawnlightsearch`
`sudo apt-get update`

If it doesn't work, you may download the deb ( [python3-dawnlightsearch_0.1.1.1-1_amd64.deb ](https://launchpad.net/~chg-hou/+archive/ubuntu/dawnlightsearch/+files/python3-dawnlightsearch_0.1.1.1-1_amd64.deb),  [python3-dawnlightsearch_0.1.1.1-1_i386.deb](https://launchpad.net/~chg-hou/+archive/ubuntu/dawnlightsearch/+files/python3-dawnlightsearch_0.1.1.1-1_i386.deb) ) or run [setup.py](https://github.com/chg-hou/DawnlightSearch/tree/master/src) to install.

**Comment by revast** [comment]
ok thanks. works now. 

Only one thing left:  why do you have libsqlite3-dev in the debian package's depends line? Is that needed for normal operation?

**Comment by chg-hou** [comment]
@revast 
The reason is that the MFT parser module [mft_c_parser_module.cpp](https://github.com/chg-hou/DawnlightSearch/blob/master/src/DawnlightSearch/MFT_parser/mft_c_parser_module.cpp) requires a header file (sqlite3.h) from libsqlited3-dev to compile.
This compilation only occur once when the whole software is being installed. You can uninstall libsqlite3-dev after installation, and it can work normally.

**Comment by revast** [comment]
uh, late answer.  thanks for detailing it out!
 Any news regarding the pure c++ version?

**Comment by revast** [comment]
btw, I hat to change 

`EditFolderDialog_base_class, _ = uic.loadUiType("Ui_edit_exclued_folder.ui")`

to
```
EditFolderDialog_base_class, _ = uic.loadUiType(
     os.path.join(os.path.dirname(os.path.abspath(__file__)), "Ui_edit_exclued_folder.ui"))
```
in Ui_change_excluded_folder_dialog.py

and

'MainWindow_base_class, _ = uic.loadUiType("Ui_mainwindow.ui")'

to 

```
MainWindow_base_class, _ = uic.loadUiType(
     os.path.join(os.path.dirname(os.path.abspath(__file__)), "Ui_mainwindow.ui"))
```
in DawnlightSearch_main.py

to get it run. was surprised, because I used the ppa version,
ubuntu 16.04, python3-pyqt5 5.5.1+dfsg-3ubuntu5~xenialoverlay11~1


now icons do not get shown, hmm

**Comment by revast** [comment]
ah, found it. the way you call DawnlightSearch is:

python3 /usr/lib/python3/dist-packages/DawnlightSearch/DawnlightSearch_main.py - but then you are not in the right directory, and DawnlightSearch will fail to find .ui and icon files.

if you cd to /usr/lib/python3/dist-packages/DawnlightSearch/  and the issue python3 DawnlightSearch_main.py, it works

so it would be best to put a bash script to /usr/bin to launch it like so:


```
#!/bin/bash
cd /usr/lib/python3/dist-packages/DawnlightSearch/
python3 DawnlightSearch_main.py "$@"
```

that would be the standard way to do it, as the program would otherwise not be callable via commandline. I am aware not that you have put Path=/usr/lib/python3/dist-packages/DawnlightSearch
in the .desktop file..

**Comment by revast** [comment]
# Some more things I witnessed:
<br />

- dock locations not as intended?

 I found that by default,  the "results dock" was left to the "database dock", I so guess the default DOCK_LOCATIONS were erratic... or was that intended? 
<br />


 - Show Location Table command ?

 the Show Location Table command in the icon toolbar does nothing.. 

```
 <sender>actionShow_Location_Table</sender>
   <signal>triggered()</signal>
   <receiver>dockWidget_uuid</receiver>
```

but dockWidget is commented out in DawnlightSearch_main.py ...
<br />


- Search... does what?

other than on the screenshot, there is a Search button on the toolbar, which I guess is the same as the Search.... in the edit menu... both seem to do nothing...

```
<connection>
   <sender>actionSearch_focus</sender>
   <signal>triggered()</signal>
   <receiver>comboBox_search</receiver>
   <slot>setFocus()</slot>
.
.
```
which focus gets set here?
<br />



-  "results dock" resize problem:

when I place the docks like in your screenshot, pressing the green toolButton_avd_setting button, the advanced settings pop out under the search bar. The icon changes then, and when I click them again, they hide, but the  "results dock", which was resized through the first click, stays resized, which is kind of bad that one has to resize it every time an advanced seach needs  to be made.

**Comment by revast** [comment]
- the right click menu on "results dock" does not work on all file types. When clicking .sh .png .svg the menu does not come up.
```

2018-02-23 20:49:52,273 - 140372850587392:get_tableview_selected:891 - root - ==== Selected : ['RS_blendOP_prev.png', '/home/hero/.config/OpenToonz/stuff/library/mypaint brushes/ramon', '/home/hero/.config/OpenToonz/stuff/library/mypaint brushes/ramon/RS_blendOP_prev.png', False]
Traceback (most recent call last):
  File "DawnlightSearch_main.py", line 816, in on_tableview_context_menu_requested
    for icon_filename, app_name, app_tooltip, app_launch_fun, app_launcher in get_open_with_app(file_type):
  File "/usr/lib/python3/dist-packages/DawnlightSearch/UI_delegate/listitem_formatter.py", line 105, in get_open_with_app
    icon_filename = get_app_icon_filename(app_info)
  File "/usr/lib/python3/dist-packages/DawnlightSearch/UI_delegate/listitem_formatter.py", line 58, in get_app_icon_filename
    icon_name = themed_icon.get_names()[0]
AttributeError: 'FileIcon' object has no attribute 'get_names'
```


- the menu in the screenshot also has a "open with"  option, which is totally missing 

oh my, I guess I should pack these in proper issues

**Comment by chg-hou** [comment]
@revast Thanks for your constructive comments. Honestly speaking, the c++ version is very far from working. Currently I don't have enough time to maintain this project. I am wondering whether I should rewrite the codes in a more neat way after Ubuntu 18.04 is released.
Maybe we should also say goodbye to sqlite and use another database that supports multi-thread.
By the way, which version will you prefer: C++ or python?

**Comment by revast** [comment]
Hi, 

- I do not think you should target solely Ubuntu, which is more work for sure, but e.g. Open(Suse)BuildServices are, once mastered and set up, a very convenient way to serve the most relevant linux distro andscape, (including Appimage), with own repositories. If such a service would be set up, this also would boost the chances of official inclusion of dawnlightsearch into the main repositories of all main distros - If thats's a valuable goal for you. 

 - apparently now also flatpack, Appimage and snap are in that game - but its hard to say which one will superseed the other(s). 


- As for database, sqlite is hard to beat in terms of simplicity and ease of use... https://sqlite.org/threadsafe.html states there is multithreading possible with sqlite, though I do not know if your usecase is covered. 

- I for my part like the C++ core and python for all non-speed critical parts. That's the way Blender does it, for example, and it does it very well. But in the End its all about maintainability - Which version you think has the cleaner concept/code and can be more inviting to be touched by others, plus can be easier deployed.

**Comment by chg-hou** [comment]
@revast 

Good news. The C++ version has finally been completed after the long wait.
Multi-thread, fast UI response, smaller file size...

- Right now building from source might be the best choice  (file size ~800KB). I have tested with snap (~100MB), appimage(~30MB), and flatpak (~50MB): the snap one is under classic confinement review; the appimage one has not been submitted yet, but it definitely works;  the flatpak one did not work properly, due to "lsblk" being restricted by the sandbox.

 - Still use SQLite. Tried with firebird, which is not easy to handle and make the program simple. The employed Qt SQL protocol should also work with other databases( [https://doc.qt.io/qt-5/sql-driver.html](https://doc.qt.io/qt-5/sql-driver.html) ) . It's something out of consideration.

- So comes the pure C++ one. I will focus on this one afterwards.

Thanks again for your suggestions. I will go through the UI problems you mentioned above later.

Build methods:
From source:  [https://github.com/chg-hou/DawnlightSearch/wiki/Build-from-source](https://github.com/chg-hou/DawnlightSearch/wiki/Build-from-source)
Flatpak etc. : [https://github.com/chg-hou/DawnlightSearch/blob/c%2B%2B-version/built_appimage_snap_flatpak.txt](https://github.com/chg-hou/DawnlightSearch/blob/c%2B%2B-version/built_appimage_snap_flatpak.txt)

**Comment by chg-hou** [comment]
Answers to questions (Feb 24)

- dock locations not as intended?

I relocated the docks. I should look better now.

- Show Location Table command ?

Show Location Table command works now.

- Search... does what?

They corresponds to the same action. I planned to add some popup windows. Will hide them.

- "results dock" resize problem:

I failed to find a short solution when put search panel in the main widget. Now the result view is move to the central widget and search is shifted to a new dock.

- the right click menu on "results dock" does not work on all file types. When clicking .sh .png .svg the menu does not come up.

Now the "open with" menu is built on KIO lib from KDE framework 5. Should be more stable.

**Comment by revast** [comment]
nice!

**Comment by revast** [comment]
hi, I have now tried to compile the QT version.

### My observations: 

* With the AppImage, the icon which is normally shown in the panel, @alt-tab etc.. not working.
* When I compile myself,  libsqlite3-dev is missing in the build dependencies list. util-linux (lsblk) in runtime dependencies
* Also, the binary is recognized as a shared library, see [here for background info](https://stackoverflow.com/questions/45329372/ubuntu-recognizes-executable-as-shared-library-and-wont-run-it-by-clicking)
    *  Adding QMAKE_LFLAGS += -no-pie to DawnlightSearch.pro fixes that.

#### Running: 
* in the Menu:  
      * Setting -> Settings  
      * Open Setting File Path ->  Open Settings File Path
      * change excluded folders  is, when opened, called edit excluded folders - maybe call it Set Excluded Folders?  Define Excluded Folders? Also first letter of words in uppercase would be more consistent.
      * File and About menu have these ... dots behind the menu items, settings menu does not. At least at Change Excluded Folders and Advanced settings would be appropriate.
     
*  "Device Minor Num" and "Major Num" are so collapsed in default view that I could only see "Device" on both, same as some columns in search results like IsFolder.. The three time columns also are misaligned, and as they always have the same content, they could have a fixed width.
* Drag&Drop out of the search results would be AWSOME to have ;-)
*  While the information in the table for the partitions is nice, It would be at least cool to have some descriptive mouse-over text which describes what each column is for.
    *  I for my part have no clue what the minor/major, alias are for..
* I also get "lang file missing: :/lang/en_US.qm"
  * the language file for english is not in the lang folder, even if I create one with qtLinguist, it does not find it either... changing Language in the program itslef works as expected, so I guess there just a little fix needed here.
* DawnLightSearch does not respect the current icon-theme, but uses the default kde icons

*  When I look at the list of devices, it shows two more than I thought it would: /dev/sr0 and /dev/sda2..

My partitions are as flollows:


blkid:
/dev/sda1: UUID="..." TYPE="ext4" PTTYPE="dos" PARTUUID="..."
/dev/sda5: UUID="" TYPE="swap" PARTUUID="..."
/dev/sdb: LABEL="vault" UUID="..." TYPE="ext4"



fdisk:
Disk /dev/sda: 60 GiB, 64424509440 bytes, 125829120 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: ...

Device     Boot    Start      End  Sectors Size Id Type
/dev/sda1  *        2048 79691775 79689728  38G 83 Linux
/dev/sda2       79693822 83884031  4190210   2G  5 Extended
/dev/sda5       79693824 83884031  4190208   2G 82 Linux swap / Solaris


Disk /dev/sdb: 164 GiB, 176093659136 bytes, 343932928 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


So /dev/sda2 is an extended partition, is this intended to be shown in DawnlightSearch?
If so, it would be nice to name it as one, otherwise it would be cool to filter it out.

Same with /dev/sr0 as possible CD-RW or similar device.. Its good that it is there as well, but maybe it is a good idea to state that there is no medium in the drive or have a switch where you can hide uncommon stuff / partitions under a certain size by default.

Thanks again for creating the QT version, I like it quite a lot!
